# Analyse the results to determine the "optimal" wind farm layout

In [11]:
import pandas as pd
import os

In [12]:
# Get all the files
directory = 'model1/'

file_paths = [os.path.join(directory, f) for f in os.listdir(directory)]

# Read in the csv files into one df

dataframes = [pd.read_csv(file) for file in file_paths]
df = pd.concat(dataframes, ignore_index=True)

df

,Test Case,Avg Dispersion,Avg Distance to Goal,Avg Clustering Coefficient,Num Flocks
0,test_baseline,59.343484,62.246687,0.999047,1
1,test_baseline,60.111251,131.478713,0.999050,1
2,test_baseline,58.762087,60.665573,0.999055,1
3,test_000,109.814509,6721.201979,0.991976,2
4,test_000,58.958183,6623.135659,0.998380,1
...,...,...,...,...,...
457,test_030,36.949769,5853.516281,0.996509,1
458,test_030,33.537574,5526.200343,0.997175,1
459,test_031,40.558266,3320.328636,0.997825,1
460,test_031,34.515855,4242.403069,0.998007,1
461,test_031,338.437198,4710.824578,0.842042,2

Groupby Test Case and get the mean for rest of columns

In [13]:
grouped_df = df.groupby('Test Case').mean().reset_index()

# Display the grouped DataFrame
grouped_df

,Test Case,Avg Dispersion,Avg Distance to Goal,Avg Clustering Coefficient,Num Flocks
0,test_000,98.718915,6452.659965,0.992880,2.000000
1,test_001,223.582892,5092.457807,0.939998,2.071429
2,test_002,119.357133,6395.243550,0.978472,1.642857
3,test_003,189.164745,6027.109077,0.959319,2.214286
4,test_004,152.407741,6684.720685,0.963946,3.000000
5,test_005,185.396309,5543.856523,0.959127,1.642857
6,test_006,126.624296,7353.360448,0.989619,1.714286
7,test_007,468.050714,6573.087756,0.885031,2.000000
8,test_008,99.550730,3582.519318,0.978450,1.357143
9,test_009,48.651685,5880.925280,0.996868,1.071429
10,test_010,366.738944,6370.759962,0.938785,2.071429
11,test_011,147.974701,4672.950603,0.946061,1.857143
12,test_012,138.545086,4121.234292,0.970849,1.428571
13,test_013,135.817244,4351.039722,0.956389,1.571429
14,test_014,155.368742,3692.955529,0.968045,1.428571
15,test_015,180.172790,3687.116761,0.942748,1.642857
16,test_016,152.339707,7486.745211,0.971043,1.857143
17,test_017,318.018515,6100.829747,0.921273,2.571429
18,test_018,187.768867,7730.172593,0.962517,2.142857
19,test_019,138.903291,4352.192034,0.939164,3.428571
20,test_020,329.080787,7886.742102,0.920066,2.571429
21,test_021,101.344018,6936.674819,0.986401,1.428571
22,test_022,121.088077,9093.766898,0.990577,1.857143
23,test_023,282.045754,8861.245321,0.957848,1.642857
24,test_024,65.968499,4159.223239,0.984008,1.214286
25,test_025,51.642468,7005.322928,0.995424,1.142857
26,test_026,154.979929,7990.456038,0.985205,1.571429
27,test_027,716.291823,7025.270324,0.827470,1.928571
28,test_028,33.179236,4005.175398,0.997118,1.000000
29,test_029,157.570788,5315.488649,0.950652,2.500000
30,test_030,106.772634,4952.922774,0.980021,1.285714
31,test_031,57.421270,3854.088939,0.986502,1.214286
32,test_baseline,62.030781,185.223577,0.999038,1.142857

Sort by parameters to see the "best"

In [14]:
sorted_df = grouped_df.sort_values(by='Avg Distance to Goal', ascending=True)
sorted_df

,Test Case,Avg Dispersion,Avg Distance to Goal,Avg Clustering Coefficient,Num Flocks
32,test_baseline,62.030781,185.223577,0.999038,1.142857
8,test_008,99.550730,3582.519318,0.978450,1.357143
15,test_015,180.172790,3687.116761,0.942748,1.642857
14,test_014,155.368742,3692.955529,0.968045,1.428571
31,test_031,57.421270,3854.088939,0.986502,1.214286
28,test_028,33.179236,4005.175398,0.997118,1.000000
12,test_012,138.545086,4121.234292,0.970849,1.428571
24,test_024,65.968499,4159.223239,0.984008,1.214286
13,test_013,135.817244,4351.039722,0.956389,1.571429
19,test_019,138.903291,4352.192034,0.939164,3.428571
11,test_011,147.974701,4672.950603,0.946061,1.857143
30,test_030,106.772634,4952.922774,0.980021,1.285714
1,test_001,223.582892,5092.457807,0.939998,2.071429
29,test_029,157.570788,5315.488649,0.950652,2.500000
5,test_005,185.396309,5543.856523,0.959127,1.642857
9,test_009,48.651685,5880.925280,0.996868,1.071429
3,test_003,189.164745,6027.109077,0.959319,2.214286
17,test_017,318.018515,6100.829747,0.921273,2.571429
10,test_010,366.738944,6370.759962,0.938785,2.071429
2,test_002,119.357133,6395.243550,0.978472,1.642857
0,test_000,98.718915,6452.659965,0.992880,2.000000
7,test_007,468.050714,6573.087756,0.885031,2.000000
4,test_004,152.407741,6684.720685,0.963946,3.000000
21,test_021,101.344018,6936.674819,0.986401,1.428571
25,test_025,51.642468,7005.322928,0.995424,1.142857
27,test_027,716.291823,7025.270324,0.827470,1.928571
6,test_006,126.624296,7353.360448,0.989619,1.714286
16,test_016,152.339707,7486.745211,0.971043,1.857143
18,test_018,187.768867,7730.172593,0.962517,2.142857
20,test_020,329.080787,7886.742102,0.920066,2.571429
26,test_026,154.979929,7990.456038,0.985205,1.571429
23,test_023,282.045754,8861.245321,0.957848,1.642857
22,test_022,121.088077,9093.766898,0.990577,1.857143